---
title: "Midterm"
author: "Cody Evans"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

Importing data

```{r}
suppressMessages(library("tidyverse"))
suppressMessages(register <- read_csv("register.csv"))
suppressMessages(sales <- read_csv("sales.csv"))
#N <- nrow(register)
```

# Original column names for the two data sets Register and Sales

### Register

```{r}
colnames(register)
```

### Sales

```{r}
colnames(sales)
```

Changing column names for better understanding

```{r}
colnames(register)[colnames(register) == "is the customer a student/faculty/staff (0) or unaffiliated (1)"] <- "unaffiliated"
colnames(register)[colnames(register) == "customer id"] <- "cid"
colnames(register)[colnames(register) == "purchase"] <- "pid"
colnames(register)[colnames(register) == "preferred customer discount"] <- "discount"
colnames(register)[colnames(register) == "contact preference"] <- "contact"

cat("Improved column names for the register data\n")
colnames(register)

colnames(sales)[colnames(sales) == "category of inventory goods"] <- "goods"

cat("Improved column names for the sales data\n")
colnames(sales)
```

## Making some Tibbles

```{r}
purchases <- tibble(pid = register$pid, item = register$item, charge = register$charge, price = register$price, unaffiliated = as.factor(register$unaffiliated), cid = register$cid, receipt = as.factor(register$receipt), contact = as.factor(register$contact), newsletter = as.factor(register$newsletter), sales = as.factor(register$sales), discount = as.factor(register$discount))

# Continue from here
song_list <- tibble(song_artist = surv$song_artist, song = surv$song, link = surv$link, name = surv$name)

tempPref <- pref[2:45]

temp <- gather(tempPref, key = "song_name", value = "rating", -name)

ratings <- tibble(persName = temp$name, songName = temp$song_name, rating = temp$rating)

people$time <- as.POSIXlt(parse_datetime(people$time, format = "%D %H:%M"))

people$major <- as.factor(people$major)

levels(people$major)
```
